version: 0.0
os: linux
files:
  - source: /target/messageUtil-1.0.jar
    destination: /home/ec2-user/app/
hooks:
  AfterInstall:
    - location: scripts/run_server.sh
      timeout: 300
      runas: ec2-user
